### ISSUE TITLE
sbatch --wrap?

### ISSUE THREAD

**Issue by kcgthb** [mbhall88/ssubmit#2]
Hi!

I'm wondering what's the advantage of running `sbatch --wrap` directly?
https://slurm.schedmd.com/sbatch.html#OPT_wrap

I get that `srun command` would be blocking and you're looking at a `sbatch`-like job submission process, but the following command would basically do that directly with `sbatch`, no submission script required, and no wrapper over regular Slurm tools either:

```
$ sbatch --mem 600 -J rsync_my_data --wrap "rsync -az src/ dest/"
```

**Comment by mbhall88** [comment]
Yes, `--wrap` handles a larger part of what ssubmit does. However, there are a few small differences. With ssubmit you can use user-friendly time and memory arguments, and also set shebang and `set` options
